language: r
sudo: false
cache: packages
dist: trusty

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE

r_binary_packages:
  - covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

r_check_args: "--as-cran --run-dontrun"

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: EzL7zwihD0vkkmy/j95DutO2otXsYaMcOQMUaZwRVvk18oTpKCK2N8OfIDnatZWMKsgJIHC8FXIHew2vmD6FemPKk0J2b87JDxwcG45Qhu/VWDbKXJF88w8SQi5KsmezzXy73OSD3UnyoHZEZzFBrMyaPNvAK0829P1zUh6SfrA=

env:
  global:
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings --as-cran"
