language: r
cache: packages
dist: trusty
os: linux

jobs:
  include:
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel
      env:
        - _R_CHECK_LENGTH_1_CONDITION_=verbose
        - _R_CHECK_LENGTH_1_LOGIC2_=verbose
        - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran --run-dontrun"

r_binary_packages:
  - covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

r_check_args: "--as-cran --run-dontrun"

notifications:
  email:
    on_success: never
    on_failure: never

env:
  global:
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings --as-cran"
